version: "3.8"
services:
  hl7-astm-parser:
    build: .
    container_name: hl7_astm_parser
    volumes:
      - .:/app
    ports:
      - 9091:9091
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    command:
      [
        "uvicorn",
        "src.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "9091",
        "--reload",
      ]
